/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.projektex.lebensmitteldatenbank;

import javax.swing.JOptionPane;

/**
 *
 * @author Cyril
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SelectionWindow1
     */
    public SignUp() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1HinterGrund = new javax.swing.JPanel();
        jPanel2Links = new javax.swing.JPanel();
        jLabel1images1Links = new javax.swing.JLabel();
        jLabel2SignUp = new javax.swing.JLabel();
        jButton1Admin = new javax.swing.JButton();
        jButton1Guest = new javax.swing.JButton();
        jButton1Close = new javax.swing.JButton();
        jPanel1Rechts = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1Unten = new javax.swing.JPanel();
        jPanel2Oben = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Selection Window");
        setUndecorated(true);
        setResizable(false);

        jPanel1HinterGrund.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1HinterGrund.setLayout(null);

        jPanel2Links.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2Links.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2Links.setLayout(null);

        jLabel1images1Links.setIcon(new javax.swing.ImageIcon("C:\\Users\\Cyril\\Documents\\NetBeansProjects\\HMACProgEx\\src\\com\\projektex\\lebensmitteldatenbank\\imag\\images1Links.jpg")); // NOI18N
        jPanel2Links.add(jLabel1images1Links);
        jLabel1images1Links.setBounds(0, 70, 240, 210);

        jPanel1HinterGrund.add(jPanel2Links);
        jPanel2Links.setBounds(0, 40, 240, 310);

        jLabel2SignUp.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel2SignUp.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2SignUp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2SignUp.setText("Sign up");
        jPanel1HinterGrund.add(jLabel2SignUp);
        jLabel2SignUp.setBounds(230, 10, 140, 90);

        jButton1Admin.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButton1Admin.setText("Admin");
        jButton1Admin.setBorder(null);
        jButton1Admin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1AdminActionPerformed(evt);
            }
        });
        jPanel1HinterGrund.add(jButton1Admin);
        jButton1Admin.setBounds(250, 110, 100, 50);

        jButton1Guest.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButton1Guest.setText("Guest");
        jButton1Guest.setBorder(null);
        jButton1Guest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1Guest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1GuestActionPerformed(evt);
            }
        });
        jPanel1HinterGrund.add(jButton1Guest);
        jButton1Guest.setBounds(250, 200, 100, 50);

        jButton1Close.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButton1Close.setText("Close");
        jButton1Close.setBorder(null);
        jButton1Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1CloseActionPerformed(evt);
            }
        });
        jPanel1HinterGrund.add(jButton1Close);
        jButton1Close.setBounds(250, 290, 100, 50);

        jPanel1Rechts.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1Rechts.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Cyril\\Documents\\NetBeansProjects\\HMACProgEx\\src\\com\\projektex\\lebensmitteldatenbank\\imag\\images2Rechts.jpg")); // NOI18N
        jPanel1Rechts.add(jLabel1);
        jLabel1.setBounds(10, 70, 220, 200);

        jPanel1HinterGrund.add(jPanel1Rechts);
        jPanel1Rechts.setBounds(360, 40, 230, 310);

        jPanel1Unten.setBackground(new java.awt.Color(10, 100, 153));
        jPanel1Unten.setLayout(null);
        jPanel1HinterGrund.add(jPanel1Unten);
        jPanel1Unten.setBounds(0, 370, 590, 30);

        jPanel2Oben.setBackground(new java.awt.Color(10, 100, 153));
        jPanel2Oben.setLayout(null);
        jPanel1HinterGrund.add(jPanel2Oben);
        jPanel2Oben.setBounds(0, 0, 590, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1HinterGrund, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1HinterGrund, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(588, 400));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1CloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1CloseActionPerformed

    private void jButton1GuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1GuestActionPerformed
        GuestLebensmittel gast = new GuestLebensmittel();
        gast.setVisible(true);
    }//GEN-LAST:event_jButton1GuestActionPerformed

    private void jButton1AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1AdminActionPerformed
        SignIn sp = new SignIn();
        sp.setVisible(true);
    }//GEN-LAST:event_jButton1AdminActionPerformed

    /**
     * @param args the command line arguments
     *//*
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         *//*
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form *//*
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Admin;
    private javax.swing.JButton jButton1Close;
    private javax.swing.JButton jButton1Guest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1images1Links;
    private javax.swing.JLabel jLabel2SignUp;
    private javax.swing.JPanel jPanel1HinterGrund;
    private javax.swing.JPanel jPanel1Rechts;
    private javax.swing.JPanel jPanel1Unten;
    private javax.swing.JPanel jPanel2Links;
    private javax.swing.JPanel jPanel2Oben;
    // End of variables declaration//GEN-END:variables
}
