/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.projektex.ebensmitteldatenbank;

import javax.swing.JOptionPane;

/**
 *
 * @author Cyril
 */
public class SelectionWindow extends javax.swing.JFrame {

    /**
     * Creates new form SelectionWindow1
     */
    public SelectionWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1Unten = new javax.swing.JPanel();
        jPanel2Links = new javax.swing.JPanel();
        jLabel1Image1 = new javax.swing.JLabel();
        jLabel2SignUp = new javax.swing.JLabel();
        jButton1Admin = new javax.swing.JButton();
        jButton1Guest = new javax.swing.JButton();
        jButton1Close = new javax.swing.JButton();
        jPanel1Rechts = new javax.swing.JPanel();
        jLabel1Immage2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Selection Window");
        setUndecorated(true);
        setResizable(false);

        jPanel1Unten.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1Unten.setLayout(null);

        jPanel2Links.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel1Image1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Cyril\\Documents\\NetBeansProjects\\HMACProgEx\\imag\\food_labelling1.png")); // NOI18N

        javax.swing.GroupLayout jPanel2LinksLayout = new javax.swing.GroupLayout(jPanel2Links);
        jPanel2Links.setLayout(jPanel2LinksLayout);
        jPanel2LinksLayout.setHorizontalGroup(
            jPanel2LinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2LinksLayout.createSequentialGroup()
                .addComponent(jLabel1Image1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2LinksLayout.setVerticalGroup(
            jPanel2LinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2LinksLayout.createSequentialGroup()
                .addComponent(jLabel1Image1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1Unten.add(jPanel2Links);
        jPanel2Links.setBounds(0, 0, 240, 410);

        jLabel2SignUp.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel2SignUp.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2SignUp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2SignUp.setText("Sign up");
        jPanel1Unten.add(jLabel2SignUp);
        jLabel2SignUp.setBounds(230, 0, 140, 90);

        jButton1Admin.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButton1Admin.setForeground(new java.awt.Color(255, 255, 255));
        jButton1Admin.setText("Admin");
        jButton1Admin.setBorder(null);
        jButton1Admin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1AdminActionPerformed(evt);
            }
        });
        jPanel1Unten.add(jButton1Admin);
        jButton1Admin.setBounds(250, 110, 100, 50);

        jButton1Guest.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButton1Guest.setForeground(new java.awt.Color(255, 255, 255));
        jButton1Guest.setText("Guest");
        jButton1Guest.setBorder(null);
        jButton1Guest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1Guest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1GuestActionPerformed(evt);
            }
        });
        jPanel1Unten.add(jButton1Guest);
        jButton1Guest.setBounds(250, 200, 100, 50);

        jButton1Close.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButton1Close.setForeground(new java.awt.Color(255, 255, 255));
        jButton1Close.setText("Close");
        jButton1Close.setBorder(null);
        jButton1Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1CloseActionPerformed(evt);
            }
        });
        jPanel1Unten.add(jButton1Close);
        jButton1Close.setBounds(250, 290, 100, 50);

        jLabel1Immage2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Cyril\\Documents\\NetBeansProjects\\HMACProgEx\\imag\\food_labelling1.png")); // NOI18N
        jLabel1Immage2.setText("jLabel1");

        javax.swing.GroupLayout jPanel1RechtsLayout = new javax.swing.GroupLayout(jPanel1Rechts);
        jPanel1Rechts.setLayout(jPanel1RechtsLayout);
        jPanel1RechtsLayout.setHorizontalGroup(
            jPanel1RechtsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1Immage2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, Short.MAX_VALUE)
        );
        jPanel1RechtsLayout.setVerticalGroup(
            jPanel1RechtsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1Immage2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, Short.MAX_VALUE)
        );

        jPanel1Unten.add(jPanel1Rechts);
        jPanel1Rechts.setBounds(360, 0, 230, 400);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1Unten, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1Unten, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(588, 403));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1CloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1CloseActionPerformed

    private void jButton1GuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1GuestActionPerformed
        GuestLebensmittel gast = new GuestLebensmittel();
        gast.setVisible(true);
    }//GEN-LAST:event_jButton1GuestActionPerformed

    private void jButton1AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1AdminActionPerformed
        SignUp sp = new SignUp();
        sp.setVisible(true);
    }//GEN-LAST:event_jButton1AdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectionWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectionWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectionWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectionWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectionWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Admin;
    private javax.swing.JButton jButton1Close;
    private javax.swing.JButton jButton1Guest;
    private javax.swing.JLabel jLabel1Image1;
    private javax.swing.JLabel jLabel1Immage2;
    private javax.swing.JLabel jLabel2SignUp;
    private javax.swing.JPanel jPanel1Rechts;
    private javax.swing.JPanel jPanel1Unten;
    private javax.swing.JPanel jPanel2Links;
    // End of variables declaration//GEN-END:variables
}
